name: Deploy to BigCommerce

on:
  push:
    branches:
      - main  # Change if deploying from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Stencil CLI
        run: |
          npm install -g @bigcommerce/stencil-cli

      - name: Authenticate with BigCommerce
        run: |
          echo "Setting up Stencil credentials..."
          mkdir -p ~/.stencil
          echo '{
            "access_token": "${{ secrets.BC_ACCESS_TOKEN }}",
            "store_hash": "${{ secrets.BC_STORE_HASH }}",
            "normal_store_url": "https://${{ secrets.BC_STORE_HASH }}.mybigcommerce.com"
          }' > ~/.stencil/stencil.json

      - name: Deploy Theme to BigCommerce
        run: |
          stencil push --ignore "*.git*" --delete --activate
